### ISSUE TITLE
QueueCreation and debugging

### ISSUE THREAD

**Issue by danielmarbach** [pablocastilla/NServiceBus.Kafka#6]
While investigating issue #4 I was wondering why a console window pops up when the acceptance tests are executed. It turns out it is the queue creator. As far as I understand you are using the batch files to create the topics necessary to run the acceptance tests. While that works it makes debugging hard. On my machine every time I try to attach the debugger to an acceptance test I get the following exception:

```
System.IO.IOException : The pipe has been ended.

   at NServiceBus.AcceptanceTesting.Support.ScenarioRunner.<Run>d__0.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTesting\Support\ScenarioRunner.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.AcceptanceTesting.ScenarioWithContext`1.<Run>d__2.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTesting\ScenarioWithContext.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.AcceptanceTesting.ScenarioWithContext`1.<NServiceBus-AcceptanceTesting-Support-IScenarioWithEndpointBehavior<TContext>-Run>d__9.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTesting\ScenarioWithContext.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at 
```

For better debugging experience I did the following:

* Replace the queue creator with an empty queue creator
* Enable 

```
# Auto create topic
auto.create.topics.enable=true
```

in `server.properties` and restarted the broker. 

I think shelling out into cmd.exe is not really a sustainable solution but unfortunately I don't have a good proposal to fix it since I'm still lacking lot of context so I'll just leave this here.

**Comment by danielmarbach** [comment]
I just realised, while submitting that maybe while waiting for [KIP-4 ](https://cwiki.apache.org/confluence/display/KAFKA/KIP-4+-+Command+line+and+centralized+administrative+operations) you could just remove the queue creation and force clients to use the auto.create.topics as described above?

**Comment by pablocastilla** [comment]
auto.create.topics.enable is enabled by default. This creates topics when you send a message, not when you subscribe to a topic.

I will double check on Monday, but the problem I saw was that if the topic is not created before the subscription process the subscription attempt is lost. So I feel that topics have to be created before subscriptions are done. If this is true I suppose we have to force installing a kafka version in local that we could reference to with the cmd :S.

I also don't like it. At least we know that when kip-4 is done we can have a clean solution.

Anyhow I will make the queue creation optional by configuration and disabled by default. How do you see it?

**Comment by danielmarbach** [comment]
Sounds reasonable. I managed to write the code for the other issue in the plane and found a few other problems. Will report on monday as well as send in the PR
